### ISSUE TITLE
no longer works after 30.11.15

### ISSUE THREAD

**Issue by Owyn** [ivantsov/HabrCommentsFilter#4]
@ivantsov 
doesn't seem to work anymore... filtering by number above 0 just hides everything
shows average rating as "0"

version 2.2, firefox, greasemonkey

example links: http://geektimes.ru/company/jowi/blog/266598/ 
http://habrahabr.ru/post/271925/

**Comment by ivantsov** [comment]
Yeah, I've noticed this yesterday as well and I'm planning to fix it as soon as possible. But currently I'm a little busy so it could take a week or so. Nevertheless, thank you for writing this issue.

**Comment by ivantsov** [comment]
Fixed in [v2.2.1](https://github.com/ivantsov/HabrCommentsFilter/releases/tag/v2.2.1) by this commit https://github.com/ivantsov/HabrCommentsFilter/commit/0575cf64421ac64cdbe94725653da08c14dc3583.
